### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by devsnek** [devsnek/edge#10]
- [x] basic custom test runner
- [x] basic wpt runner
- [ ] write tests for everything
